language: rust
rust:
    - stable

before_script:
    - "export PATH=$HOME/.meteor:$PATH"
    - mysql -e 'CREATE DATABASE test_football_matome;'
    - nvm install 6
    - nvm use 6
    - npm install -g yarn
    - cargo install diesel_cli
    - make migrate

services:
    - mysql

cache: yarn

script:
    - make travis
    - make test
    - cd ./client/ && make
    - make test

git:
    submodules: false
