language: rust
rust:
    - stable

dist: trusty
sudo: required
addons:
    apt:
        packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6

before_script:
    - "export PATH=$HOME/.meteor:$PATH"
    # node update
    - nvm install 6
    - nvm use 6
    - npm install -g yarn
    # install cargo env dependency
    - cargo install diesel_cli
    # create database
    - mysql -e 'CREATE DATABASE test_football_matome;'

cache: yarn

script:
    - make travis
    - make migrate
    - make test
    - cd ./client/ && make
    - make test

git:
    submodules: false
