language: rust
rust:
    - stable

before_script:
    - "export PATH=$HOME/.meteor:$PATH"
    - mysql -e 'CREATE DATABASE test_football_matome;'

services:
    - mysql

cache: yarn

script:
    - make travis
    - make test
    - cd ./client/ && npm install -g yarn && make
    - make test

git:
    submodules: false
